### ISSUE TITLE
Decimal values

### ISSUE THREAD

**Issue by SeafireGit** [frankrousseau/kyou#12]
Hello,
It would be nice to be able to add decimal values, and note only integer. Could be useful to quantify weight for instance ;)

Thanks for the great job !

**Comment by frankrousseau** [comment]
Thank you @SeafireGit for your enhancement proposal. I don't when I will have time to work on it, but it's something I will investigate first, the next time I work on Kyou.

**Comment by frankrousseau** [comment]
Hi @SeafireGit,

Decimal values are now allowed for custom trackers (`1.2` not `1,2`). Can you tell me if it works after updating Kyou?

**Comment by SeafireGit** [comment]
Sounds good to me, thanks :)

**Comment by frankrousseau** [comment]
Great!
