### ISSUE TITLE
Decimal values in graph

### ISSUE THREAD

**Issue by SeafireGit** [frankrousseau/kyou#13]
Hello,
Following #12 , decimal value are allowed, but are not reported in the graph when flying over a point. Is it possible to show the exact value on the graph too ?

**Comment by frankrousseau** [comment]
Thank you for reporting. I will check that.

**Comment by frankrousseau** [comment]
I pushed a new version of Kyou. Can you try it?

**Comment by SeafireGit** [comment]
Sorry for the delay.
Looks perfect to me !!
Thanks !
