### ISSUE TITLE
Possible data source confusion between trackers?

### ISSUE THREAD

**Issue by twitwi** [frankrousseau/kyou#14]
I tried to build a new tracker from the Withings data: each weight document contains not only the "weight" but also the "fatWeight".
I thus tried to create a new tracker by mostly copying the existing one, changing its name and the map function:
- https://github.com/twitwi/kyou/commits/master
- https://github.com/twitwi/kyou/commit/e1b9f54462186b636b1c7280d50eee72604f38a8

When I both display trackers, they show the same values: currently, when I test, they both show my weight. NB: in earlier tests, I have also had a instance where they were both showing the fatWeight (on both graphs) so the "map" function is probably ok.

Any guidance on what I might be missing or doing wrong is welcome.
Thanks for the project.

**Comment by frankrousseau** [comment]
It looks like a bug in Kyou, whatever thank you for reporting! I will check tonight what's wrong.

**Comment by frankrousseau** [comment]
Ok, it's a case that was already handled but not documented. Can you add a `requestName` field to your tracker?

**Comment by twitwi** [comment]
That works! Thanks a lot.
I might make it a clean contribution at some point (but I can see it won't be very soon).
