### ISSUE TITLE
Hide empty graphs

### ISSUE THREAD

**Issue by bnjbvr** [frankrousseau/kyou#6]
My girlfriend is very confused by the fact that although she only uses one tracker, all graphs are shown in her kyou instance. Could we instead hide the graphs that have no associated data at all?

**Comment by frankrousseau** [comment]
Yes, that's something I should do since a long time. If I'm not alone using KYou, it's something I will consider.

**Comment by frankrousseau** [comment]
It's now possible with the latest version of Kyou. Thank you for your report @bnjbvr
